#Deriving the latest base image
FROM python:latest


#Labels as key value pair
LABEL Maintainer="flossedmeat"


# Any working directory can be chosen as per choice like '/' or '/home' etc
# i have chosen /usr/app/src
WORKDIR /usr/local/bin/raspPingTest

#to COPY the remote file at working directory in container
COPY .env ./
COPY ensureWifiConnection.py ./
COPY raspberryNetworkTest.py ./
COPY raspProbeLogging.py ./
COPY sendToServer.py ./
# Now the structure looks like this '/usr/app/src/test.py'


#CMD instruction should be used to run the software
#contained by your image, along with any arguments.

CMD [ "python", "./raspberryNetworkTest.py"]